apiVersion: v1
kind: Service
metadata:
  name: eta-db-service
spec:
  #   type: NodePort
  selector:
    app: eta-db
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
    - name: mongo-express
      protocol: TCP
      port: 8081
      targetPort: 8081
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: eta-db-service-express
# spec:
#   type: NodePort
#   selector:
#     app: eta-db
#   ports:
#     - name: http
#       port: 8081
